### ISSUE TITLE
Exception Error Message

### ISSUE THREAD

**Issue by rrone** [cerad/ng2016#140]
Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://graph.facebook.com/oauth/access_token` resulted in a `400 Bad Request` response: {"error":{"message":"Code was invalid or expired. ","type":"OAuthException","code":100,"fbtrace_id":"EOptoTexOnX"}} in /home/ahundiak/ws2016/ng2016/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:107 Stack trace: #0 /home/ahundiak/ws2016/ng2016/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 /home/ahundiak/ws2016/ng2016/vendor/guzzlehttp/promises/src/Promise.php(201): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 /home/ahundiak/ws2016/ng2016/vendor/guzzlehttp/promises/src/Promise.php(154): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array) #3 /home/ahundiak/ws2016/ng2016/vendor/guzzlehttp/promises/src/TaskQueue.php(61): GuzzleHttp\Promise\Promise::GuzzleHttp\Pro in /home/ahundiak/ws2016/ng2016/var/bootstrap.php.cache on line 2971

**Comment by rrone** [comment]
Worked on 2nd attempt.

**Comment by ahundiak** [comment]
Looks like it might be down in the bowels of guzzle.  I'll take a look but I have never gotten this before.  Tried googling the error but nothing relevant.  Was this in production?  I would not have expected the exception message to be shown.  That is something we need to deal with.

**Comment by rrone** [comment]
Yes, in production.  Note that when I tried again, it worked.

rick
310.920.8209
web.ayso@gmail.com

**Comment by ahundiak** [comment]
Confirmed that exceptions are being shown in production.  Not sure why yet.

**Comment by ahundiak** [comment]
All exceptions in production now silently redirect to home.
