### ISSUE TITLE
Implement Team Management Functionality

### ISSUE THREAD

**Issue by rrone** [cerad/ng2016#144]
- Update http://local.ng2016/game/listing: move registered Team table to top
- Add Team Export function
- Add Team Import function: Imports coach name and region number and updates ng2016games.regTeams.regTeamName, .orgId, .orgView with appropriately formatted name & ids
- Add game/listing link on Admin page under Team Management

**Comment by rrone** [comment]
Need help on routing the test upload.  the modal success dialog is asynchronous from the page refresh.

TODO:
[ ]	4. Add AbstractImporter for xlsx : file to data array
[ ]	5. Extend AbstractImport to RegTeamImport:  data array to objects
[ ]	6. Add RegTeamTest
[ ]	7. Add Soccerfest points export
[ ]	8. Add Soccerfest points import

**Comment by ahundiak** [comment]
I took a look at your code.  Good job.

The only immediate suggestion would be to divide it into individual
Export/Import routes.  Little bit confusing to try and use one route for
both.

I think if we separate then the import routine can show a nice message
after importing and take care of the quick redirect problem.

On the hand, you may have your reasons so we can discuss during the call.

**Comment by rrone** [comment]
Closed with PR #182
