### ISSUE TITLE
Fix undefined routes

### ISSUE THREAD

**Issue by rrone** [cerad/ng2016#154]
Unknown url, e.g. /pdf, cause exceptions in Routing component.  Should handle this by redirect to welcome.

`Fatal error: Uncaught Symfony\Component\Routing\Exception\ResourceNotFoundException in /home/ahundiak/ws2016/ng2016/var/cache/prod/appProdUrlMatcher.php:261 Stack trace: #0 /home/ahundiak/ws2016/ng2016/var/cache/prod/classes.php(702): appProdUrlMatcher->match('/images/') #1 /home/ahundiak/ws2016/ng2016/vendor/symfony/symfony/src/Symfony/Component/Routing/Router.php(256): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request)) #2 /home/ahundiak/ws2016/ng2016/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php(101): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request)) #3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher)) #4 /home/ahundiak/ws2016/ng2016/vendor/symfony/symfony/src/Symfony/Component/Ev in /home/ahundiak/ws2016/ng2016/var/bootstrap.php.cache on line 2971`

**Comment by rrone** [comment]
will close with PR #158

**Comment by ahundiak** [comment]
Fixed by catching all exceptions and redirecting to home in production.  Leave development alone.
