### ISSUE TITLE
/schedule/assignor exports fail

### ISSUE THREAD

**Issue by rrone** [cerad/ng2016#189]
Both excel & text

**Comment by rrone** [comment]
AppBundle\Action\Schedule2016\Assignor\ScheduleAssignorViewFile is missing

**Comment by ahundiak** [comment]
This is sort of by design.  It is basically not yet implemented.

**Comment by rrone** [comment]
Do we need these exports anyway ?  Perhaps just delete the buttons.

**Comment by rrone** [comment]
Update schedule and assignor filter to start on today only
