### ISSUE TITLE
Update 2014 instructions & post on home page

### ISSUE THREAD

**Issue by rrone** [cerad/ng2016#208]

**Comment by rrone** [comment]
Include Soccerfest instructions

**Comment by rrone** [comment]
Soccerfest instructions:
[AYSO_NG_2016_Soccerfest_Coach_Information.pdf](https://github.com/cerad/ng2016/files/335779/AYSO_NG_2016_Soccerfest_Coach_Information.pdf)
[AYSO_NG_2016_Soccerfest.HowToDoIt.pdf](https://github.com/cerad/ng2016/files/335780/AYSO_NG_2016_Soccerfest.HowToDoIt.pdf)

**Comment by rrone** [comment]
FOR REVIEW: 20160627.Instruction--RefereeSelfAssignment

[20160627.Instruction--RefereeSelfAssignment.pdf](https://github.com/cerad/ng2016/files/335788/20160627.Instruction--RefereeSelfAssignment.pdf)

**Comment by rrone** [comment]
Updated: 
[20160627-1.Instruction--RefereeSelfAssignment.pdf](https://github.com/cerad/ng2016/files/339442/20160627-1.Instruction--RefereeSelfAssignment.pdf)

**Comment by ahundiak** [comment]
Not trying to nitpick but:

5. Click the **“Referee Schedules”** menu item under “Referees”.

Should be REQUEST ASSIGNMENTS

====
17. You may view your schedule by selecting
“My Schedule” under the “Referee
Schedule” or “My Account” menu items. 

My Schedule is under My Stuff.  Would actually be kind of nice if it was under Referees as well.

Two other things you might consider adding:

- Try to only signup for back to back games on the same field.  With the way games are scheduled, even getting to an adjacent field could be challenging if a field gets behind schedule.

- Limit yourself to no more than 4 games per day.  Going to be hot and muggy.

**Comment by rrone** [comment]
Good to be at the nitpick stage.  

Tom is writing a comprehensive instruction for all Referee functions.  Will upload when done editing.

rick
310.920.8209
web.ayso@gmail.com

**Comment by rrone** [comment]
Updated instructions:  
[Referee Self-Assigning Message 20160628-2.pdf](https://github.com/cerad/ng2016/files/341166/Referee.Self-Assigning.Message.20160628-2.pdf)

Updated Soccerfest instruction: 
[AYSO_NG_2016_Soccerfest_Coach_Information.pdf](https://github.com/cerad/ng2016/files/341167/AYSO_NG_2016_Soccerfest_Coach_Information.pdf)

**Comment by rrone** [comment]
Closing.  Moving the posting to Issue #269
