### ISSUE TITLE
Is unapproved filter working correctly

### ISSUE THREAD

**Issue by ahundiak** [cerad/ng2016#236]
From the admin person listing page, only a couple of referees show up as being unapproved.  My son was not among them.  The AdminViewFilters has:

```
                case 'Unapproved':
                    if (isset($person['roles']['ROLE_REFEREE'])) {
                        //if (!$personView->approved AND !$personView->hasCertIssues()) {
                        if (!$personView->approved) {
                            $listPersons[] = $person;
                        }
                    }

```
I commented out the original line and added what I think it should be.  Seems to give the correct results.  But I wanted to make sure before merging.  Maybe I am using the form wrong.

On a different issue, from the admin listing form is I change Will Coach from Yes to No then Will Coach shows up blank on the listing form.  Not a big deal at this point but seems a bit odd.

**Comment by rrone** [comment]
I think it is correct as is.  I set the reports up as two steps: 1) referees with certification issues and 2) those without issues but unapproved.

Those with issues are not ready to be approved.  The report “Referees with Issues” includes your son who has certification issues (in my local db).

rick
310.920.8209
web.ayso@gmail.com

**Comment by ahundiak** [comment]
Works as designed.
