### ISSUE TITLE
Table borders under chrome seem to have disappeared

### ISSUE THREAD

**Issue by ahundiak** [cerad/ng2016#242]
Think it happened recently.  I had noticed that it was harder to read the schedules under chrome.  Looked under firefox and the borders were back.  

Under chrome:
![image](https://cloud.githubusercontent.com/assets/130533/16362227/584c7b80-3b6e-11e6-9b05-bfe478502dbe.png)

Under firefox:
![image](https://cloud.githubusercontent.com/assets/130533/16362232/8223ca62-3b6e-11e6-85fb-a44991a6fc5e.png)

**Comment by rrone** [comment]
Will close with PR #245

**Comment by rrone** [comment]
Closed with PR #245
