### ISSUE TITLE
Printing Requirements

### ISSUE THREAD

**Issue by ahundiak** [cerad/ng2016#256]
Who will be responsible for actually printing game day schedules (mostly for referee check in)?

I have a good printer which I can bring if needed.

I also don't mind doing the printing.  Just be nice to know upfront.

Might also build a game day report all nicely formatted for printing if I knew it would be used.

**Comment by rrone** [comment]
Shouldn’t need the printer.

A modified version of the Assignor Export would do for Referee checkin.  The only additional field other that what is displayed in the browser was cell phone info.  The current export has much more but could be hidden in Excel before printing.  A custom export would save that step.

NO opinion is that the Browser print should be sufficient for game day reports.
