### ISSUE TITLE
Add Export views to project/person/admin/listing

### ISSUE THREAD

**Issue by rrone** [cerad/ng2016#71]
Excel & CSV

**Comment by rrone** [comment]
Looking for comments on export contents

**Comment by ahundiak** [comment]
I merged in the latest master branch and pushed it up.  Need to a git pull on the branch.

I changed the defaults for registered and verified in ProjectPersonRepository::findByProjectkey to null so they would pickup the Sombero folks who have not signed in.

There is no need for a csv export.  This page is for admins and we can assume that everyone has a spreadsheet program available.  Exporting on a phone is probably not a valid use case.  And while I am on the subject, the Export to Text on the schedule pages was meant to export and actual text file that could then be printed by a referee or maybe sent as an email.  I don't see a real need for a csv file.  

The actual export seems fine for now.

We will want to enhance it a bit to allow some imports.  Need to add a project key and person column (you can hide them) so we can absolutely identify the person during import.  Want to add an Approved column as well so we can do mass approvals. This is all future stuff.

We might want to add a sheet with notes.  There are actually two note properties, one filled in by the user and one by the administrator.  Sombero referees have some examples.

I think we will also want to "pretty" things up a bit.  In particular we want to set column widths.  You can take a look here for an example: https://github.com/cerad/arbiter2016/blob/master/src/AppBundle/Action/Avail/AvailReporterExcel.php

Eventually we will want to break out the views into individual sheet templates.  The sheet template render would be called with a worksheet object as well as a list of people.  It would then render just the sheet.  This in turn will allow us to stitch together large spreadsheets.  In particular, we will eventually want a spreadsheet showing a summary of assignments for each referee as well as each individual assignment as well as who is available for medal rounds etc.  Moving each of these sheets into their own template will help keep things organized.  Maybe.

But again, what you have now is fine.

**Comment by rrone** [comment]
Closed with PR #103 Feature#71 add export views to project person admin listing
